services:
  tenant-manager:
    image: jferme/tenant-manager:latest
    container_name: tenant-manager-homelab
    restart: unless-stopped
    ports:
      - "5999:5999"
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/app/data/tenant_manager.db
      - LOG_LEVEL=debug
      - BACKUP_INTERVAL=24
      - HOST=0.0.0.0
    volumes:
      # Local directory mounts for easy access and backup
      - ./data:/app/data
      - ./backups:/app/backups
      - ./logs:/app/logs
      - ./alerts:/app/alerts
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5999/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 30s
    networks:
      - homelab-network

networks:
  homelab-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16